export enum ActivityTypes {
    FOOTBALL = 'FOOTBALL',
    VOLLEYBALL = 'VOLLEYBALL',
    DANCES = 'DANCES',
    PAINT_BALL = 'PAINT_BALL',
    ESCAPE_ROOM = 'ESCAPE_ROOM',
    SWIMMING_POOL = 'SWIMMING_POOL'
}
